### ISSUE TITLE
sync: operation not supported on network drive

### ISSUE THREAD

**Issue by aa15032261** [spacemeshos/post#267]
postcli doesn't seem to work if the datadir is set to a network drive on macOS.

So I made a patch that works for me:
https://github.com/aa15032261/post/commit/26156437789a3c57f660f4439d597a456a293107

**Comment by fasmat** [comment]
The primary reason we started using `atomic.WriteFile` was because we had several instances where data was written to disk but not flushed resulting in empty files.

I looked into this topic again and your code does the same as `atomic.WriteFile` with the exception that `os.WriteFile` doesn't call `Sync` on the data before it returns. Meaning it could result in the file being empty when it replaces the existing file, so be careful! 🙂
